# Generated by Django 3.0.2 on 2020-01-21 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minigames', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotoGameModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barrel', models.IntegerField(default=None)),
                ('ticket', models.TextField(default=None, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='UserIdModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='BarrelModel',
        ),
        migrations.DeleteModel(
            name='TicketModel',
        ),
        migrations.AddField(
            model_name='lotogamemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minigames.UserIdModel'),
        ),
    ]
