# Generated by Django 3.0.2 on 2020-02-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minigames', '0002_auto_20200121_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotogamemodel',
            name='barrel',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lotogamemodel',
            name='ticket',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
