# Generated by Django 3.0.2 on 2020-02-08 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minigames', '0003_auto_20200208_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotogamemodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='minigames.UserIdModel'),
        ),
    ]
