# Generated by Django 3.0.2 on 2020-01-13 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playeruser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
